### ISSUE TITLE
Better file management

### ISSUE THREAD

**Issue by TheGroundZero** [dracula/homer#3]
To install this theme I ran `git clone https://github.com/dracula/homer.git /www/assets/themes/dracula` and then used the following lines in my `/www/assets/config.yml`:
```yaml
stylesheet:
  - "assets/themes/dracula/custom.css"
```

I did have to update the `custom.css` file a tiny bit:
```css
#app.theme-default.is-dark #bighead {
    background-image: url("dracula-background.png");
    // ...
}
```

Ideally, however, you would be able to use e.g. `theme: dracula` instead (see https://github.com/bastienwirtz/homer/blob/018344d9116b506c662ecdcee2d0d505c857f1cf/docs/configuration.md?plain=1#L41)
